Parser is ready
vkamiansky/analysis-practice-jul-2019 pull request #1
Opened 2019-06-27 10:45 UTC by Shurron

2019-06-27 12:36 UTC, vkamiansky requested changes
Требуются некоторые правки.

2019-06-27 12:36 UTC, vkamiansky commented on Models/Person.cs
> +			return HashCode.Combine(Name, Email);
Здесь, на мой взгляд равенство должно определяться по email'у, а для hash-кода лучше использовать id человека.

2019-06-27 12:36 UTC, vkamiansky commented on Models/Question.cs
> +			return HashCode.Combine(QuestionText, AnswersList, CorrectAnswerIndex);
Это неверный подход к формированию hash-кода. См. 3 свойства, которыми должен обладать hash-код

2019-06-27 14:33 UTC, vkamiansky requested changes
Требуются изменения.

2019-06-27 14:33 UTC, vkamiansky commented on Parser.cs
> +		public List<Test> ParseFile(string path)
Предлагается заменить Test на PersonTestResult.

2019-06-27 14:33 UTC, vkamiansky commented on Parser.cs
> +		public List<Test> ParseFile(string path)
По памяти предпочтительно возвращать `IEnumerable<PersonTestResult>`

2019-06-27 14:33 UTC, vkamiansky commented on Parser.cs
> +	public class Parser
CsvQuizResultsParser + проверка формата.

2019-06-27 14:33 UTC, vkamiansky commented on Parser.cs
> +	{
Возвращать Result, по которому будет понятно правильный формат файла или нет.

2019-06-28 10:37 UTC, Shurron commented on Models/Person.cs
> +			return HashCode.Combine(Name, Email);
`GetHashCode()` должен возвращать одинаковые значения для одинаковых экземпляров. Так что, по-моему мнению, он должен отражать логику `Equals()`: оба метода должны использовать одни и те же поля объекта. Предлагаю оставить как есть, либо в обоих методах использовать только поле Email, либо в обоих методах использовать только id.

Правильно раздать id всем экземплярам Person не так просто в связи с тем, что в данных существуют абсолютно одинаковые экземпляры, и им нужно выдать одинаковые id. Для этого придется проектировать какой-нибудь пул объектов Person, основанный на `HashSet` например. Задача этого пула - правильно выдать id новому экземпляру. Проблема заключается в том, что коллекция внутри пула будет вызывать метод `GetHashCode()`, основанный на id, а id нового объекта еще не сгенерирован.

Остается два варианта: оставить как есть, либо в обоих методах использовать только поле Email.

2019-06-28 12:00 UTC, Shurron commented on Parser.cs
> +		public List<Test> ParseFile(string path)
Исправлено в [Some improvements](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/f17d47d720471dd5688c1551d986b5a9002b6389)

2019-06-28 12:01 UTC, Shurron commented on Parser.cs
> +		public List<Test> ParseFile(string path)
Исправлено в [Some improvements](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/f17d47d720471dd5688c1551d986b5a9002b6389)

2019-06-28 12:01 UTC, Shurron commented on Parser.cs
> +	public class Parser
Изменено на CsvParser в [Some improvements](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/f17d47d720471dd5688c1551d986b5a9002b6389)

2019-06-28 12:02 UTC, Shurron commented on Parser.cs
> +	{
Исправлено в [Some improvements](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/f17d47d720471dd5688c1551d986b5a9002b6389)

2019-06-28 13:17 UTC, vkamiansky commented on Models/Person.cs
> +			return HashCode.Combine(Name, Email);
Я бы предлагал в Equals использовать стандартную реализацию, и не переопределять её, а в `GetHashCode()` использовать  поле `Id`.

См. [статью](https://docs.microsoft.com/ru-ru/visualstudio/ide/reference/generate-equals-gethashcode-methods?view=vs-2019) Microsoft на эту тему.

2019-07-03 10:15 UTC, Shurron commented on Models/Person.cs
> +			return HashCode.Combine(Name, Email);
Удалил этот метод в [Deleted redundant methods](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/389241fd240a5c32d9758f099cbf891d969d2206)

2019-07-03 10:15 UTC, Shurron commented on Models/Question.cs
> +			return HashCode.Combine(QuestionText, AnswersList, CorrectAnswerIndex);
Удалил этот метод в [Deleted redundant methods](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/389241fd240a5c32d9758f099cbf891d969d2206)

2019-07-03 13:35 UTC, vkamiansky approved these changes

2019-07-03 13:35 UTC, merged