Added text output to file
vkamiansky/analysis-practice-jul-2019 pull request #17
Opened 2019-07-12 11:10 UTC by Shurron

Completed issue #16

2019-07-12 15:07 UTC, vkamiansky requested changes
Requires a unit test project.

2019-07-12 15:07 UTC, vkamiansky commented on src/QuizData.TextReport/TextReporter.cs
> +		public static void ToFile(string path, DataAnalyserReport report)
Add ability to test this via streams.

2019-07-15 14:06 UTC, vkamiansky approved these changes

2019-07-15 14:06 UTC, vkamiansky requested changes
Add test for reporter.

2019-07-16 11:01 UTC, Shurron commented
> Add test for reporter.

Done in [Added one unit test for TextReporter](https://github.com/vkamiansky/analysis-practice-jul-2019/commit/7476a87b65d3de28d53d9c6222df6a094a946e2a)

2019-07-16 14:36 UTC, vkamiansky approved these changes

2019-07-16 14:44 UTC, merged